name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Authenticate Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          mkdir ./keys
          echo '${{ secrets.CREDENTIALS }}' > ./keys/credentials.json
          ls
          ls ./keys
          docker build --tag ${{ vars.GAR_LOCATION }}/backend .

      - name: Push image
        run: docker push ${{ vars.GAR_LOCATION }}

      - name: Run Docker Image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_HOST_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_HOST_KEY }}
          port: 22
          script: |
            docker container rm -f chefies-backend
            docker image rm -f chefies-backend
            docker run --name chefies-backend -e GOOGLE_APPLICATION_CREDENTIALS="/app/keys/credentials.json" -d --restart always -p 9000:80 ${{ vars.GAR_LOCATION }}/backend
